# Pre-commit hooks for Mycodo
# Install with: pip install pre-commit && pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - sqlalchemy[mypy]
        exclude: ^(mycodo/tests/|alembic_db/)
