name: Linting

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install ruff flake8 black isort
    
    - name: Run Ruff (fast linter)
      run: |
        ruff check mycodo/ --output-format=github || true
      continue-on-error: true
    
    - name: Check code formatting with Black
      run: |
        black --check mycodo/ --diff || true
      continue-on-error: true
    
    - name: Check import sorting
      run: |
        isort --check-only mycodo/ --diff || true
      continue-on-error: true
    
    - name: Run Flake8
      run: |
        flake8 mycodo/ \
          --max-line-length=120 \
          --ignore=E203,E266,E501,W503,F403,F401 \
          --max-complexity=18 \
          --select=B,C,E,F,W,T4,B9 \
          || true
      continue-on-error: true
