name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ ! "$PR_TITLE" =~ ^(\[WIP\]|\[Phase\ [0-9]+\]|feat|fix|docs|refactor|test|chore): ]]; then
          echo "❌ PR title must start with [WIP], [Phase N], or conventional commit type"
          exit 1
        fi
        echo "✅ PR title format valid"
    
    - name: Check for merge conflicts
      run: |
        git fetch origin master
        if ! git merge-tree $(git merge-base HEAD origin/master) origin/master HEAD | grep -q "^changed in both"; then
          echo "✅ No merge conflicts detected"
        else
          echo "⚠️ Warning: Potential merge conflicts detected"
        fi
    
    - name: Check file count
      run: |
        FILES_CHANGED=$(git diff --name-only origin/master...HEAD | wc -l)
        echo "Files changed: $FILES_CHANGED"
        if [ $FILES_CHANGED -gt 50 ]; then
          echo "⚠️ Warning: Large PR with $FILES_CHANGED files"
        else
          echo "✅ Reasonable PR size"
        fi
    
    - name: Check for required files
      run: |
        # For modernization PRs, check if tests exist
        if [[ "${{ github.event.pull_request.title }}" =~ Modernization ]]; then
          if git diff --name-only origin/master...HEAD | grep -q "test_"; then
            echo "✅ Tests included in modernization PR"
          else
            echo "⚠️ Warning: No test files detected in modernization PR"
          fi
        fi
    
    - name: Comment PR validation results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const output = `## PR Validation Results
          
          ✅ PR checks completed
          
          **PR Size:** ${context.payload.pull_request.changed_files} files
          **Lines Changed:** +${context.payload.pull_request.additions}/-${context.payload.pull_request.deletions}
          
          **Next Steps:**
          - [ ] Review automated test results
          - [ ] Check type checking results
          - [ ] Verify linting passes
          - [ ] Manual code review
          
          *Automated by PR Checks workflow*`;
          
          // Only comment once
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.data.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('PR Validation Results')
          );
          
          if (!botComment) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
          }
